---
# Deploy example
- name: Deploy example
  hosts: all

  tasks:
    - name: ping
      ansible.builtin.ping:
    - name: Copy static file
      become: true
      ansible.builtin.copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
    - name: Append datetime
      become: true
      ansible.builtin.shell: |
        date >>/usr/share/nginx/html/index.html
    - name: Display variable 
      ansible.builtin.debug:
        msg: "hello"
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/ellery-tsai/deploy-example.git'
        dest: /tmp/checkout
        version: master
